# -*- coding: utf-8 -*-
"""23-1-25(2nd code)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11hkLY347Y-m4effYowylPyUJN2Y2pVYy
"""

import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

data = {
    'square_feet_area': [8500, 9600, np.nan, 11250, np.nan, 9550, 14260, np.nan, 13830, 11500],
    'year_built': [2003, 1976, 2001, np.nan, 1998, 2000, 2006, 1978, 1950, np.nan],
    'overall_condition': [5, 8, 6, 7, np.nan, 7, 8, 6, np.nan, 7],
    'ready_to_move': ['Yes', 'No', 'No', np.nan, 'No', np.nan, 'No', 'Yes', 'No', 'Yes'],
    'sale_price': [350000, 450000, np.nan, 550000, np.nan, 475000, 600000, np.nan, 575000, 495000]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)
numeric_imputer=SimpleImputer(strategy='mean')
df['square_feet_area'] = numeric_imputer.fit_transform(df[['square_feet_area']])
df['year_built'] = numeric_imputer.fit_transform(df[['year_built']])

df['square_feet_area'].fillna(df['square_feet_area'].mean(), inplace=True)
df['year_built'].fillna(df['year_built'].median(), inplace=True)
df['overall_condition'].fillna(df['overall_condition'].mode()[0], inplace=True)
df['ready_to_move'].fillna(df['ready_to_move'].mode()[0], inplace=True)
df['sale_price'].fillna(df['sale_price'].mean(), inplace=True)

print("\nDataFrame after handling missing values:")
print(df)