# -*- coding: utf-8 -*-
"""24-1-25(3)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sRLa6oMVna43vpeRXRV5sZwanFo_4Nhk
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

np.random.seed(10)
data = pd.DataFrame({
    'value':np.concatenate([np.random.normal(0,1,100),np.random.normal(10,1,10)])

})
Q1 = data['value'].quantile(0.25)
Q3 = data['value'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = data[(data['value'] < lower_bound) | (data['value'] > upper_bound)]
print(f"Outliers based on Box Plot criteria:\n{outliers}")

plt.figure(figsize=(12,6))

plt.subplot(1, 2, 1)
sns.boxplot(data['value'])
plt.title('Box Plot')

plt.subplot(1, 2, 2)
sns.histplot(data['value'], kde=True)
plt.title('Histogram')

plt.tight_layout()
plt.show