# -*- coding: utf-8 -*-
"""24-1-25(1)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_v9fQQwZHchwPVMYL8CRQl1wXyeFIg94
"""

import pandas as pd
data = pd.DataFrame({'value':[1,2,3,4,5,6,7,8,9,10,100]})
Q1 = data['value'].quantile(0.25)
Q3 = data['value'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = data[(data['value'] < lower_bound) | (data['value'] > upper_bound)]
print(outliers)