# -*- coding: utf-8 -*-
"""27-1-25(3)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bF9fTVcuW2ohWK8-kRCW24Fc0LobXShD
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler

data = {
    "Age": [25, 30, 35, 40, 45],
    "height":[150, 160, 170, 180, 190],
    "weight":[50, 60, 70, 80, 90]
}

df = pd.DataFrame(data)
print("Orginal dataframe:")
print(df)

scaler = StandardScaler()
StandardScaler_data = scaler.fit_transform(df)
df_scaled = pd.DataFrame(StandardScaler_data, columns=df.columns)
print("\nScaled dataframe:")
print(df_scaled)