# -*- coding: utf-8 -*-
"""27-1-25(1)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tXsSfC6J5picf0UmDwXZLlDEYqAqu0DY
"""

import pandas as pd
from sklearn.preprocessing import MinMaxScaler

data = {
    "Age": [25, 30, 35, 40, 45],
    "height":[150, 160, 170, 180, 190],
    "weight":[50, 60, 70, 80, 90]
}

df = pd.DataFrame(data)
print(df)

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(df)
print(scaled_data)