# -*- coding: utf-8 -*-
"""28-1-25(2)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GzuWE8WSHh3i3YJx9H4FEBmkA4FkBLnZ
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

data = {
    'Customer_ID': [1,2,3,4,5],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 40, 45],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
}

df = pd.DataFrame(data)
print("Original dataframe: ")
print(df)

label_encoder = LabelEncoder()
df['color_encoded'] = label_encoder.fit_transform(df['color'])
df['gender_encoded'] = label_encoder.fit_transform(df['gender'])

print("\nDataframe after encoding: ")
print(df)