# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c3LBiRL65YWl6Jv5C02NSTzmvb6j4qr6
"""

import matplotlib.pyplot as plt
data = [5, 7, 7, 8, 9, 10, 10, 10, 11, 12, 11, 11]
plt.hist(data, bins=10, edgecolor='black')  # Corrected edgecolor syntax
plt.title('Simple Histogram Example')
plt.xlabel('Numbers')
plt.ylabel('Count')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
datf = pd.DataFrame({"Season 1":[7,4,5,6,3],
                     "Season 2":[1,2,8,4,9]})
p = sns.histplot(data =datf)
p.set(xlabel="X Label Value", ylabel="Y Label Value")
plt.show

import matplotlib.pyplot as plt
import numpy as np

np.random.seed(42)
data = np.random.randint(20, 81, 1000)
plt.hist(data, bins=15, edgecolor='green', color='pink')
plt.title('Histogram of Cancer Patients Age Distribution')
plt.xlabel('Age')
plt.ylabel('Number of Patients')
plt.show()