# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18M4TsbsVtyabJeY6FmgjIo23zfupchCJ
"""

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

np.random.seed(42)
def createdata():
  data={
      'Age':np.random.randint(18,70,size=20),
      'Salary':np.random.randint(30000,120000,size=20),
      'Purchased':np.random.choice([0,1],size=20),
      'Gender':np.random.choice(['Male','Female'],size=20),
      'City':np.random.choice(['New york','Los Angeles','Chicago','Houston','Miami'],size=20)

  }
  df=pd.DataFrame(data)
  return df

df=createdata()
df.head(10)

df.loc[5,'Age']=np.nan
df.loc[9,'Salary']=np.nan
df.head(10)

from re import T
df['Age'].fillna(df['Age'].mean(),inplace=True)
df['Salary'].fillna(df['Salary'].mean(),inplace=True)

df.head(10)

df_dropped=df.dropna()
df_dropped.head(10)

96666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666

from sklearn.impute import KNNImputer
knn_imputer=KNNImputer(n_neighbors=5)
df[['Age','Salary']]=knn_imputer.fit_transform(df[['Age','Salary']])

df.head(10)

from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()
df['Gender']=label_encoder.fit_transform(df['Gender'])
df.head(10)

