# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c3LBiRL65YWl6Jv5C02NSTzmvb6j4qr6
"""

import matplotlib.pyplot as plt
data = [5, 7, 7, 8, 9, 10, 10, 10, 11, 12, 11, 11]
plt.hist(data, bins=10, edgecolor='black')  # Corrected edgecolor syntax
plt.title('Simple Histogram Example')
plt.xlabel('Numbers')
plt.ylabel('Count')
plt.show()

